-- MySQL Script generated by MySQL Workbench
-- Thu Mar  4 18:41:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema registro_asistencia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema registro_asistencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registro_asistencia` DEFAULT CHARACTER SET utf8 ;
USE `registro_asistencia` ;

-- -----------------------------------------------------
-- Table `registro_asistencia`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_asistencia`.`alumnos` (
  `idalumnos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(150) NOT NULL,
  `especialidad` VARCHAR(100) NULL,
  PRIMARY KEY (`idalumnos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro_asistencia`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_asistencia`.`materias` (
  `idmateria` INT NOT NULL AUTO_INCREMENT,
  `materia` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idmateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro_asistencia`.`asistencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_asistencia`.`asistencias` (
  `idasistencia` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `idalumnos` INT NULL,
  `idmateria` INT NULL,
  PRIMARY KEY (`idasistencia`),
  -- INDEX `fk_idalumnos_idx` (`idalumnos` ASC) VISIBLE,
  -- INDEX `fk_idmateria_idx` (`idmateria` ASC) VISIBLE,
  CONSTRAINT `fk_idalumnos_asistencia`
    FOREIGN KEY (`idalumnos`)
    REFERENCES `registro_asistencia`.`alumnos` (`idalumnos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_idmateria_asistencia`
    FOREIGN KEY (`idmateria`)
    REFERENCES `registro_asistencia`.`materias` (`idmateria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro_asistencia`.`alumno_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_asistencia`.`alumno_materia` (
  `idalumnos` INT NOT NULL,
  `idmateria` INT NOT NULL,
  -- INDEX `fk_alumnos_idx` (`idalumnos` ASC) VISIBLE,
  -- INDEX `fk_materia_idx` (`idmateria` ASC) VISIBLE,
  CONSTRAINT `fk_alumnos`
    FOREIGN KEY (`idalumnos`)
    REFERENCES `registro_asistencia`.`alumnos` (`idalumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia`
    FOREIGN KEY (`idmateria`)
    REFERENCES `registro_asistencia`.`materias` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro_asistencia`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_asistencia`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(100) NOT NULL,
  `password` VARCHAR(520) NOT NULL,
  `correo` VARCHAR(100) NULL,
  `tipo` VARCHAR(100) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro_asistencia`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_asistencia`.`grupos` (
  `idgrupo` INT NOT NULL AUTO_INCREMENT,
  `grupo` VARCHAR(45) NULL,
  `turno` VARCHAR(45) NULL,
  PRIMARY KEY (`idgrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro_asistencia`.`grupo_alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_asistencia`.`grupo_alumno` (
  `idgrupo` INT NULL,
  `idalumnos` INT NULL,
  -- INDEX `fk_idalumnos_idx` (`idalumnos` ASC) VISIBLE,
  -- INDEX `fk_idgrupo_idx` (`idgrupo` ASC) VISIBLE,
  CONSTRAINT `fk_idgrupo`
    FOREIGN KEY (`idgrupo`)
    REFERENCES `registro_asistencia`.`grupos` (`idgrupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_idalumnos`
    FOREIGN KEY (`idalumnos`)
    REFERENCES `registro_asistencia`.`alumnos` (`idalumnos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
